image: golang:1.5
git:
  path: github.com/vjscjp304/mapi2
script:
  - echo "build commands"
  - .shipped/build
  - .shipped/test
clone:
  path: github.com/vjscjp304/mapi2
build:
  image: golang:1.5
  commands:
    - echo "build commands"
    - .shipped/build
    - .shipped/test
publish:
  docker:
    file: ./Dockerfile
    username: $$docker_user
    password: $$docker_key
    registry: $$docker_registry
    repo: $$docker_repo
    email: $$docker_user_email
    tag: $$COMMIT
    


notify:
  webhook:
    image: shippedrepos-docker-drone.bintray.io/drone-webhook
    urls:
      - "https://api.ciscoshipped.io/webhooks/drone"
    on_success: true
    on_failure: true
